### ISSUE TITLE
Unhandled onError event during build

### ISSUE THREAD

**Issue by michaldudek** [newrelic-experimental/netlify-plugin#8]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

I installed the plugin through Netlify UI, configured all according to the [blog post](https://www.netlify.com/blog/netlify-and-new-relic-plugin-quickstart?utm_campaign=Changelog&utm_medium=email&_hsmi=205330821&_hsenc=p2ANqtz-_H0PooLLDD1hkRxSIoJPoBxc55jJnOpdJU2KMtm5Vfp20mj4dDni9fA33Hvjpic_mPD4jY5W7ddpdBOwUpcFq-5SXV9w&utm_content=205330821&utm_source=hs_email) about the plugin, but I'm getting build error when deploying my site.

## Description

[NOTE]: # ( Describe the problem you're encountering. )
[TIP]:  # ( Do NOT give us access or passwords to your New Relic account or API keys! )

As above.

## Steps to Reproduce

[NOTE]: # ( Please be as specific as possible. )

I was following the steps from the blog post linked above.

The site is a Create React App project if that's relevant.

## Expected Behavior

[NOTE]: # ( Tell us what you expected to happen. )

The build to not fail :)

But if there's a configuration error on my side (e.g. wrong ingest key?), surface that error.

## Relevant Logs / Console output

[NOTE]: # ( Please provide specifics of the local error logs, Browser Dev Tools console, etc. if appropriate and possible. )

```
1:12:12 PM: ────────────────────────────────────────────────────────────────
1:12:12 PM:   3. @newrelic/netlify-plugin (onBuild event)                   
1:12:12 PM: ────────────────────────────────────────────────────────────────
1:12:12 PM: ​
1:12:12 PM: ​
1:12:12 PM: ────────────────────────────────────────────────────────────────
1:12:12 PM:   4. @newrelic/netlify-plugin (onError event)                   
1:12:12 PM: ────────────────────────────────────────────────────────────────
1:12:12 PM: ​
1:12:12 PM: ​
1:12:12 PM: (@newrelic/netlify-plugin onError completed in 6ms)
1:12:12 PM: ​
1:12:12 PM: ────────────────────────────────────────────────────────────────
1:12:12 PM:   5. @newrelic/netlify-plugin (onEnd event)                     
1:12:12 PM: ────────────────────────────────────────────────────────────────
1:12:12 PM: ​
1:12:12 PM: ​
1:12:12 PM: (@newrelic/netlify-plugin onEnd completed in 8ms)
1:12:12 PM: ​
1:12:12 PM: ────────────────────────────────────────────────────────────────
1:12:12 PM:   Plugin "@newrelic/netlify-plugin" internal error              
1:12:12 PM: ────────────────────────────────────────────────────────────────
1:12:12 PM: ​
1:12:12 PM:   Error message
1:12:12 PM:   UnhandledRejection: a promise was rejected but not handled: Error: function httpAdapter(config) {
1:12:12 PM:     return new Promise(function dispatchHttpRequest(resolvePromise, rejectPromise)...<omitted>...
1:12:12 PM:   } could not be cloned.
1:12:12 PM:     return new Promise(function dispatchHttpRequest(resolvePromise, rejectPromise)...<omitted>...
1:12:12 PM:   } could not be cloned.
1:12:12 PM: ​
1:12:12 PM:   Plugin details
1:12:12 PM:   Package:        @newrelic/netlify-plugin
1:12:12 PM:   Version:        1.0.1
1:12:12 PM:   Repository:     git+https://github.com/newrelic-experimental/netlify-plugin.git
1:12:12 PM:   npm link:       https://www.npmjs.com/package/@newrelic/netlify-plugin
1:12:12 PM:   Report issues:  https://github.com/newrelic-experimental/netlify-plugin/issues
1:12:12 PM: ​
1:12:12 PM:   Error location
1:12:12 PM:   In "onBuild" event in "@newrelic/netlify-plugin" from Netlify app
1:12:12 PM:       at writeChannelMessage (node:internal/child_process/serialization:82:9)
1:12:12 PM:       at process.target._send (node:internal/child_process:839:17)
1:12:12 PM:       at process.target.send (node:internal/child_process:739:19)
1:12:12 PM:       at node:internal/util:360:7
1:12:12 PM:       at new Promise (<anonymous>)
1:12:12 PM:       at bound  (node:internal/util:346:12)
1:12:12 PM:       at sendEventToParent (file:///opt/buildhome/node-deps/node_modules/@netlify/build/src/plugins/ipc.js:123:46)
1:12:12 PM:       at handleError (file:///opt/buildhome/node-deps/node_modules/@netlify/build/src/plugins/child/error.js:13:9)
1:12:12 PM:       at Object.handleProcessError [as log] (file:///opt/buildhome/node-deps/node_modules/@netlify/build/src/plugins/child/error.js:31:9)
1:12:12 PM:       at logEvent (file:///opt/buildhome/node-deps/node_modules/log-process-errors/build/src/handle/common.js:53:12)
1:12:12 PM: ​
1:12:12 PM:   Resolved config
1:12:12 PM:   build:
1:12:12 PM:     command: npm run build
1:12:12 PM:     commandOrigin: ui
1:12:12 PM:     environment:
1:12:12 PM:       - ENABLE_BROWSER_MONITORING
1:12:12 PM:       - NEWRELIC_ACCOUNT_ID
1:12:12 PM:       - NEWRELIC_APP_ID
1:12:12 PM:       - NEWRELIC_BROWSER_LICENSE_KEY
1:12:12 PM:       - NEWRELIC_INGEST_LICENSE_KEY
1:12:12 PM:       - REACT_APP_COOKIES_DOMAIN
1:12:12 PM:       - REACT_APP_FB_PIXEL_ID
1:12:12 PM:       - REACT_APP_GRAPHQL_API_ENDPOINT
1:12:12 PM:       - REACT_APP_GRAPHQL_SUBSCRIPTIONS_API_ENDPOINT
1:12:12 PM:       - REACT_APP_GTM_TRACKING_ID
1:12:12 PM:       - REACT_APP_LIVE_MODE
1:12:12 PM:       - REACT_APP_REST_API_ENDPOINT
1:12:12 PM:       - REACT_APP_SEGMENT_API_KEY
1:12:12 PM:       - REACT_APP_SENTRY_DSN
1:12:12 PM:       - SENTRY_AUTH_TOKEN
1:12:12 PM:       - SENTRY_ORG
1:12:12 PM:       - SENTRY_PROJECT
1:12:12 PM:       - SKIP_PREFLIGHT_CHECK
1:12:12 PM:     publish: /opt/build/repo/build
1:12:12 PM:     publishOrigin: ui
1:12:12 PM:   headers:
1:12:12 PM:     - for: /static/*.woff
      values:
        Cache-Control: public, max-age=31536000, immutable
    - for: /static/*.woff2
      values:
        Cache-Control: public, max-age=31536000, immutable
    - for: /*
      values:
        Strict-Transport-Security: max-age=63072000; includeSubDomains; preload
  headersOrigin: config
  plugins:
    - inputs: {}
      origin: ui
      package: '@newrelic/netlify-plugin'
  redirects:
    - from: /*
      status: 200
      to: /index.html
```

## Your Environment

[TIP]:  # ( Include as many relevant details about your environment as possible. )

## Additional context

[TIP]:  # ( Add any other context about the problem here. )

**Comment by atido** [comment]
Hello,
I encounter exactly the same problem.
Do you know what could be the cause?

Thank you in advance.

**Comment by marc-wittwer** [comment]
I followed the netlify blogpost:
https://www.netlify.com/blog/netlify-and-new-relic-plugin-quickstart

And received the same error.

Thanks for anyone looking into it.

**Comment by andrelas1** [comment]
I found the same issue when I tried using it by following the docs as well. Not sure if it's an issue on the plugin, given that it's in an experimental state, or something missing in the docs.

**Comment by jcountsNR** [comment]
Hi all, are there any updates on this issue? Do we at least have Jira ticket open for this?

**Comment by CavalcanteLeo** [comment]
I'm getting the same error

<img width="1006" alt="Screen Shot 2022-10-27 at 23 54 06" src="https://user-images.githubusercontent.com/1735944/198482761-cfaa2be2-d7dd-480c-8189-b432c7ac36c9.png">

**Comment by annbeemsterboer** [comment]
any update regarding this issue? 👀

**Comment by SG60** [comment]
> any update regarding this issue? 👀

I think my pull request (https://github.com/newrelic-experimental/netlify-plugin/pull/11) fixes these issues. But this project doesn't seem to be maintained, and no-one from new relic has even commented on the PR. 😢

**Comment by ptahdunbar** [comment]
Hi @michaldudek @SG60 @annbeemsterboer @CavalcanteLeo @andrelas1 @marc-wittwer @atido -- #12 has been merged. Please confirm if you're still experiencing this issue.

**Comment by SG60** [comment]
> Hi @michaldudek @SG60 @annbeemsterboer @CavalcanteLeo @andrelas1 @marc-wittwer @atido -- #12 has been merged. Please confirm if you're still experiencing this issue.

That was my fork, which I've been using for a couple of months without any issues.
